'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PlayerPane from "./playerpane";
import NavPane from "./navpane";
import { RefObject, useRef } from "react";
import AudioProvider from "@/components/audiocontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    type AudioContextObject = {
        audioElement: RefObject<HTMLAudioElement | null>
    }

    // References to the audio player
    const audioElement = useRef<HTMLAudioElement>(null);

  return (
    <html lang="en">
        <head>
            
        </head>

        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh flex flex-col`}
        >

            <audio
                ref={audioElement}
                preload="true"
                loop
                autoPlay
                src={undefined}
            ></audio>

            <NavPane/>
            <AudioProvider audio={audioElement}>
                <div className="bg-gray-50 flex-2">
                        {children}  
                </div>
                <PlayerPane/>
            </AudioProvider>

        </body>
    </html>
  );
}
